export const REALTIME_EVENT_TYPES = {
  WS_CONNECTED: 'WS_CONNECTED',
  PONG: 'PONG',
  SUPPORT_TICKET_CREATED: 'SUPPORT_TICKET_CREATED',
  SUPPORT_MESSAGE_CREATED: 'SUPPORT_MESSAGE_CREATED',
  SUPPORT_STATUS_UPDATED: 'SUPPORT_STATUS_UPDATED',
  USER_NOTIFICATION_CREATED: 'USER_NOTIFICATION_CREATED',
} as const;

export type RealtimeEventType = (typeof REALTIME_EVENT_TYPES)[keyof typeof REALTIME_EVENT_TYPES];
