export const mockProducts = [
  {
    id: '1',
    name: 'Laptop Gaming ASUS ROG Strix G15',
    price: 25990000,
    oldPrice: 28990000,
    image: 'https://picsum.photos/seed/laptop1/400/400',
    rating: 4.8,
    reviews: 124,
    isNew: true,
    isFlashSale: true,
    discount: 10,
    sold: 85,
    category: 'Laptop',
    brand: 'ASUS',
    specs: {
      cpu: 'Intel Core i7 12700H',
      ram: '16GB DDR5',
      storage: '512GB SSD NVMe',
      screen: '15.6" FHD 144Hz',
      battery: '90Wh',
    }
  },
  {
    id: '2',
    name: 'MacBook Pro 14 M3 Pro 2023',
    price: 49990000,
    oldPrice: null,
    image: 'https://picsum.photos/seed/macbook/400/400',
    rating: 4.9,
    reviews: 89,
    isNew: true,
    isFlashSale: false,
    discount: 0,
    sold: 42,
    category: 'Laptop',
    brand: 'Apple',
    specs: {
      cpu: 'Apple M3 Pro',
      ram: '18GB Unified',
      storage: '512GB SSD',
      screen: '14.2" Liquid Retina XDR',
      battery: '72.4Wh',
    }
  },
  {
    id: '3',
    name: 'Điện thoại Samsung Galaxy S24 Ultra',
    price: 31990000,
    oldPrice: 33990000,
    image: 'https://picsum.photos/seed/s24/400/400',
    rating: 4.7,
    reviews: 256,
    isNew: false,
    isFlashSale: true,
    discount: 5,
    sold: 92,
    category: 'Phone',
    brand: 'Samsung',
    specs: {
      cpu: 'Snapdragon 8 Gen 3',
      ram: '12GB',
      storage: '256GB',
      screen: '6.8" Dynamic AMOLED 2X',
      battery: '5000mAh',
    }
  },
  {
    id: '4',
    name: 'Tai nghe Bluetooth Sony WH-1000XM5',
    price: 7490000,
    oldPrice: 8490000,
    image: 'https://picsum.photos/seed/sony/400/400',
    rating: 4.6,
    reviews: 412,
    isNew: false,
    isFlashSale: false,
    discount: 11,
    sold: 156,
    category: 'Audio',
    brand: 'Sony',
    specs: {
      cpu: 'V1 Processor',
      ram: 'N/A',
      storage: 'N/A',
      screen: 'N/A',
      battery: '30h',
    }
  },
  {
    id: '5',
    name: 'Màn hình LG UltraGear 27" 2K 144Hz',
    price: 8990000,
    oldPrice: 10990000,
    image: 'https://picsum.photos/seed/lg/400/400',
    rating: 4.5,
    reviews: 78,
    isNew: false,
    isFlashSale: true,
    discount: 18,
    sold: 64,
    category: 'Monitor',
    brand: 'LG',
    specs: {
      cpu: 'N/A',
      ram: 'N/A',
      storage: 'N/A',
      screen: '27" Nano IPS 2K 144Hz',
      battery: 'N/A',
    }
  },
  {
    id: '6',
    name: 'Bàn phím cơ Keychron Q1 Pro',
    price: 4590000,
    oldPrice: 4990000,
    image: 'https://picsum.photos/seed/keychron/400/400',
    rating: 4.8,
    reviews: 112,
    isNew: true,
    isFlashSale: false,
    discount: 8,
    sold: 35,
    category: 'Accessories',
    brand: 'Keychron',
    specs: {
      cpu: 'N/A',
      ram: 'N/A',
      storage: 'N/A',
      screen: 'N/A',
      battery: '4000mAh',
    }
  }
];

