// ─── Barrel exports for API services ────────────────────────────
export { default as authService } from './services/authService';
export { default as productService } from './services/productService';
export { default as categoryService } from './services/categoryService';
export { default as brandService } from './services/brandService';
export { default as orderService } from './services/orderService';
export { default as cartService } from './services/cartService';
export { default as couponService } from './services/couponService';
export { default as feedbackService } from './services/feedbackService';
export { default as flashSaleService } from './services/flashSaleService';
export { default as userService } from './services/userService';
export { default as notificationService } from './services/notificationService';
export { default as ticketService } from './services/ticketService';
export { default as wishlistService } from './services/wishlistService';
export { default as addressService } from './services/addressService';
export { default as cmsService } from './services/cmsService';
export { default as dashboardService } from './services/dashboardService';
export { default as chatbotService } from './services/chatbotService';
